### ISSUE TITLE
Publish article about RVM targeted at React users

### ISSUE THREAD

**Issue by BigAB** [canjs/react-view-model#10]

**Comment by chasenlehara** [comment]
Here’s a rough draft: https://docs.google.com/a/jupiterjs.com/document/d/1Y9GotzmQwQ2CTBNg3-3fUuO6z9rhrzZutP2GfDkdIew/edit?usp=sharing

**Comment by chasenlehara** [comment]
https://www.bitovi.com/blog/introducing-react-view-model-mvvm-with-react
