### ISSUE TITLE
Proposal: put ViewModel instance on this.state instead of this.props

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/react-view-model#58]
It has been suggested that the current setup misuses props, and that the ViewModel instance should be placed on this.state instead of this.props. That the viewModel is a dynamic (mutable) thing and is better part of state than props. Props (in react world) always represented what was on the component tag itself (passed down from above). The parent component is responsible for setting new props. The initial state of a component can be derived from props, but the props remain as they were set by the parent.

If we make this change, this.props would act as it always did in normal react, and this.state would be coopted as the ViewModel instance. The render function provided to reactViewModel would be called with 2 arguments: props and state.

**Comment by andrejewski** [comment]
Yes, using `state` is definitely preferred over `props`. Props are a component's relationship to the outside, parent or otherwise, and state is internal. I'd go as far as to say the distinction should be made even more clear by using a `this.viewModel` and documenting the second argument to reactViewModel as `viewModel` not `state`. In my mind, it is better to teach something new than try to overload an existing construct so critical to regular React components that it would lead to confusion. The `this.viewModel` may need a proposal all its own, but this is how I have done similar React observable integrations; though your technical limitations are most likely different.

**Comment by BigAB** [comment]
To weigh in here with my opinion:

I originally envisioned **React-View-Models** (RVM) as a **higher-order component** (HoC), that enhances a ["Dumb / Presentational Component"](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) into a ["Smart / Container Component"](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) like [Recompose](https://github.com/acdlite/recompose), or [React-Redux](https://github.com/reactjs/react-redux)'s `connect`.

HoCs are a very well known and accepted pattern for component composition in the React eco-system, and RVMs behaviour would therefore be consistent with current norms.

The idea that is key to HoCs is that the dumb component only takes props and renders stuff, so the HoC/Enhancer sort of ends up being a "props proxy" and "rendering hijacker" sort of thing, it's a very cool pattern, and makes composition of small, easily testable pieces into more complex components a breeze.

**RVM** never quite got to my (recently decided) optimally desired API:
```
const EnhancedComponent = withViewModel( DefineMapClass )( DumbComponent )
```
...but the idea of enhancing a dumb component into a smart component was always there.

So, I see nothing wrong with props being the thing that ends up being passed to the connected or dumb component.

That being said, I am not sure what this proposal is gong to change with the current implementation.
According to the docs the `viewModel` isn't on `this.props` anyway is it? It seems to be passed in as an argument to the "render" function.

```
reactViewModel( 'AppComponent', ViewModel, (props) => (<div>{props.name}</div>) )
```
...so is there really any difference if you document it:
```
reactViewModel( 'AppComponent', ViewModel, (viewModel) => (<div>{viewModel.name}</div>) )
```
...?

I would be against adding a second parameter:
```
const AppComponent = reactViewModel( 'AppComponent', ViewModel, (props, viewModel) => (<div>{viewModel.name}</div>) )
```
...as it breaks the idea of the HoC a little, and is odd in the sense that, what is `props` at that point?
Is it just the props passed into the "Enhanced Component"? Maybe, I don't know. It just get's further away from the Easy to understand HoC idea, but I suppose I am not against it. You'd probably want to render every time prop changed then, even if nothing in the viewModel caused a change event at that point.

**Regardless, the notion of `this.state` seems irrelevant here. It is an implementation detail as near as I can tell, nothing to do with how the user will use the library.**

The change to:
```
const AppComponent = reactViewModel( 'AppComponent', ViewModel, ( props ) => (<div>{this.state.name}</div>) )
```
Seems, odd, and arbitrary, but nothing I have strong feelings about anyway.

The strong feelings **I do have**, are that I wanted RVM to behave much like [Recompose's `withState()`](https://github.com/acdlite/recompose/blob/master/docs/API.md#withstate), where the state part of it, is abstracted away, and separated from the component, and only added to a component to enhance it and decide when rendering happened. I wanted this before I had ever discovered Recompose, but Recompose matches my mental model so well, it clarified and reinforced what I wanted from RVMs API.

 Now, as an implementation detail there is one thing to consider about putting the `viewModel` in the returned components `state`. If the viewModel is set on `this.state`, then it's shows up in React-Dev-Tools when inspecting components, which is a small, but maybe interesting thought.

So... yeah, long story short (too late), what would this proposal actually change? I am probably not against it, but what are we making the user change? What is the concept we are tying to pass onto RVM users?
